### ISSUE TITLE
Question: Can I accept NTLM requests and route based on user?

### ISSUE THREAD

**Issue by irishismyname** [caddyserver/ntlm-transport#6]
I have an unsecured REST API that I'd like to secure using this module, but I can't get a grip on what it does. I need to put a reverse proxy in front of my API that can accept NTLM authentication and route the request based on the username, OU, etc. Is that what this module is for or do I need to use something like [Caddy Security](https://authp.github.io/) for that?

**Comment by mholt** [comment]
Thanks for the question! This _proxies_ NTLM-authenticated services, as far as I know. I actually don't know too much about NTLM since I don't use it; this was just a fun weekend project a long time ago, since NTLM commits some HTTP travesties.

Since NTLM has specific restrictions regarding connection pooling/reuse, this special transport handles that, but it doesn't itself do any authentication. You'll need something like Caddy Security, is my guess. I'm not sure if it supports NTLM though.

Good luck!
